# This is a basic workflow to help you get started with Actions

name: Publish release

# Controls when the action will run. 
on:
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Run publish
        id: publish
        run: sbt -J-Xmx2G -J-Xss20M -J-XX:ReservedCodeCacheSize=128m -Dsbt.color=always -Dsbt.supershell=false "publish"
        env:
          BINTRAY_USER: secrets.BINTRAY_USER
          BINTRAY_PASS: secrets.BINTRAY_PASS
