name: Publish release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-github:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 15
        - name: Publish package
          run: sbt -J-Xmx2G -J-Xss20M -J-XX:ReservedCodeCacheSize=128m -Dsbt.color=always -Dsbt.supershell=false "publish"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}