name: Release scribe
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'release version'
        required: true
      nextVersion:
        description: 'next version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: release sbt
        run: |
          git config --local user.email "scribe-github-actions@users.noreply.github.com"
          git config --local user.name "scribe-github-actions"
          sbt "release with-defaults release-version ${{ github.event.inputs.releaseVersion }} next-version ${{ github.event.inputs.nextVersion }}"
      - name: push tag
        uses: ad-m/github-push-action@master
        with:
          branch: master
          tags: true
          github_token: ${{ secrets.GITHUB_TOKEN}}
